import type { Car } from "../util/carType";

const mockData = [
    {
      position: 1,
      number: 44,
      driver: "Lewis Hamilton",
      car: "Mercedes",
      laps: 58,
      gap: "+0.000s",
      lastLap: "1:33.456", // Added lastLap
      bestLap: "1:32.456",
      maxSpeed: "320 km/h",
      pits: 1,
    },
    {
      position: 2,
      number: 33,
      driver: "Max Verstappen",
      car: "Red Bul",
      laps: 58,
      gap: "+1.234s",
      lastLap: "1:33.789", // Added lastLap
      bestLap: "1:32.789",
      maxSpeed: "318 km/h",
      pits: 1,
    },
    {
        position: 1,
        number: 44,
        driver: "Lewis Hamilton",
        car: "Mercedes",
        laps: 58,
        gap: "+0.000s",
        lastLap: "1:33.456", // Added lastLap
        bestLap: "1:32.456",
        maxSpeed: "320 km/h",
        pits: 1,
      },
      {
        position: 2,
        number: 33,
        driver: "Max Verstappen",
        car: "Red Bul",
        laps: 58,
        gap: "+1.234s",
        lastLap: "1:33.789", // Added lastLap
        bestLap: "1:32.789",
        maxSpeed: "318 km/h",
        pits: 1,
      },
      {
        position: 1,
        number: 44,
        driver: "Lewis Hamilton",
        car: "Mercedes",
        laps: 58,
        gap: "+0.000s",
        lastLap: "1:33.456", // Added lastLap
        bestLap: "1:32.456",
        maxSpeed: "320 km/h",
        pits: 1,
      },
      {
        position: 2,
        number: 33,
        driver: "Max Verstappen",
        car: "Red Bul",
        laps: 58,
        gap: "+1.234s",
        lastLap: "1:33.789", // Added lastLap
        bestLap: "1:32.789",
        maxSpeed: "318 km/h",
        pits: 1,
      },
      {
        position: 1,
        number: 44,
        driver: "Lewis Hamilton",
        car: "Mercedes",
        laps: 58,
        gap: "+0.000s",
        lastLap: "1:33.456", // Added lastLap
        bestLap: "1:32.456",
        maxSpeed: "320 km/h",
        pits: 1,
      },
      {
        position: 2,
        number: 33,
        driver: "Max Verstappen",
        car: "Red Bul",
        laps: 58,
        gap: "+1.234s",
        lastLap: "1:33.789", // Added lastLap
        bestLap: "1:32.789",
        maxSpeed: "318 km/h",
        pits: 1,
      },
      {
        position: 1,
        number: 44,
        driver: "Lewis Hamilton",
        car: "Mercedes",
        laps: 58,
        gap: "+0.000s",
        lastLap: "1:33.456", // Added lastLap
        bestLap: "1:32.456",
        maxSpeed: "320 km/h",
        pits: 1,
      },
      {
        position: 2,
        number: 33,
        driver: "Max Verstappen",
        car: "Red Bul",
        laps: 58,
        gap: "+1.234s",
        lastLap: "1:33.789", // Added lastLap
        bestLap: "1:32.789",
        maxSpeed: "318 km/h",
        pits: 1,
      },
      {
          position: 1,
          number: 44,
          driver: "Lewis Hamilton",
          car: "Mercedes",
          laps: 58,
          gap: "+0.000s",
          lastLap: "1:33.456", // Added lastLap
          bestLap: "1:32.456",
          maxSpeed: "320 km/h",
          pits: 1,
        },
        {
          position: 2,
          number: 33,
          driver: "Max Verstappen",
          car: "Red Bull",
          laps: 58,
          gap: "+1.234s",
          lastLap: "1:33.789", // Added lastLap
          bestLap: "1:32.789",
          maxSpeed: "318 km/h",
          pits: 1,
        },
        {
          position: 1,
          number: 44,
          driver: "Lewis Hamilton",
          car: "Mercedes",
          laps: 58,
          gap: "+0.000s",
          lastLap: "1:33.456", // Added lastLap
          bestLap: "1:32.456",
          maxSpeed: "320 km/h",
          pits: 1,
        },
        {
          position: 2,
          number: 33,
          driver: "Max Verstappen",
          car: "Red Bull",
          laps: 58,
          gap: "+1.234s",
          lastLap: "1:33.789", // Added lastLap
          bestLap: "1:32.789",
          maxSpeed: "318 km/h",
          pits: 1,
        },
        {
          position: 1,
          number: 44,
          driver: "Lewis Hamilton",
          car: "Mercedes",
          laps: 58,
          gap: "+0.000s",
          lastLap: "1:33.456", // Added lastLap
          bestLap: "1:32.456",
          maxSpeed: "320 km/h",
          pits: 1,
        },
        {
          position: 2,
          number: 33,
          driver: "Max Verstappen",
          car: "Red Bull",
          laps: 58,
          gap: "+1.234s",
          lastLap: "1:33.789", // Added lastLap
          bestLap: "1:32.789",
          maxSpeed: "318 km/h",
          pits: 1,
        }, {
            position: 1,
            number: 44,
            driver: "Lewis Hamilton",
            car: "Mercedes",
            laps: 58,
            gap: "+0.000s",
            lastLap: "1:33.456", // Added lastLap
            bestLap: "1:32.456",
            maxSpeed: "320 km/h",
            pits: 1,
          },
          {
            position: 2,
            number: 33,
            driver: "Max Verstappen",
            car: "Red Bull",
            laps: 58,
            gap: "+1.234s",
            lastLap: "1:33.789", // Added lastLap
            bestLap: "1:32.789",
            maxSpeed: "318 km/h",
            pits: 1,
          },
          {
              position: 1,
              number: 44,
              driver: "Lewis Hamilton",
              car: "Mercedes",

              laps: 58,
              gap: "+0.000s",
              lastLap: "1:33.456", // Added lastLap
              bestLap: "1:32.456",
              maxSpeed: "320 km/h",
              pits: 1,
            },
            {
              position: 2,
              number: 33,
              driver: "Max Verstappen",
              car: "Red Bull",
              laps: 58,
              gap: "+1.234s",
              lastLap: "1:33.789", // Added lastLap
              bestLap: "1:32.789",
              maxSpeed: "318 km/h",
              pits: 1,
            },
            {
              position: 1,
              number: 44,
              driver: "Lewis Hamilton",
              car: "Mercedes",

              laps: 58,
              gap: "+0.000s",
              lastLap: "1:33.456", // Added lastLap
              bestLap: "1:32.456",
              maxSpeed: "320 km/h",
              pits: 1,
            },
            {
              position: 2,
              number: 33,
              driver: "Max Verstappen",
              car: "Red Bull",
              laps: 58,
              gap: "+1.234s",
              lastLap: "1:33.789", // Added lastLap
              bestLap: "1:32.789",
              maxSpeed: "318 km/h",
              pits: 1,
            },
            {
              position: 1,
              number: 44,
              driver: "Lewis Hamilton",
              car: "Mercedes",

              laps: 58,
              gap: "+0.000s",
              lastLap: "1:33.456", // Added lastLap
              bestLap: "1:32.456",
              maxSpeed: "320 km/h",
              pits: 1,
            },
            {
              position: 2,
              number: 33,
              driver: "Max Verstappen",
              car: "Red Bull",
              laps: 58,
              gap: "+1.234s",
              lastLap: "1:33.789", // Added lastLap
              bestLap: "1:32.789",
              maxSpeed: "318 km/h",
              pits: 1,
            },
            {
                position: 1,
                number: 44,
                driver: "Lewis Hamilton",
                car: "Mercedes",

                laps: 58,
                gap: "+0.000s",
                lastLap: "1:33.456", // Added lastLap
                bestLap: "1:32.456",
                maxSpeed: "320 km/h",
                pits: 1,
              },
              {
                position: 2,
                number: 33,
                driver: "Max Verstappen",
                car: "Red Bull",
                laps: 58,
                gap: "+1.234s",
                lastLap: "1:33.789", // Added lastLap
                bestLap: "1:32.789",
                maxSpeed: "318 km/h",
                pits: 1,
              },
              {
                  position: 1,
                  number: 44,
                  driver: "Lewis Hamilton",
                  car: "Mercedes",

                  laps: 58,
                  gap: "+0.000s",
                  lastLap: "1:33.456", // Added lastLap
                  bestLap: "1:32.456",
                  maxSpeed: "320 km/h",
                  pits: 1,
                },
                {
                  position: 2,
                  number: 33,
                  driver: "Max Verstappen",
                  car: "Red Bull",
                  laps: 58,
                  gap: "+1.234s",
                  lastLap: "1:33.789", // Added lastLap
                  bestLap: "1:32.789",
                  maxSpeed: "318 km/h",
                  pits: 1,
                },
                {
                  position: 1,
                  number: 44,
                  driver: "Lewis Hamilton",
                  car: "Mercedes",

                  laps: 58,
                  gap: "+0.000s",
                  lastLap: "1:33.456", // Added lastLap
                  bestLap: "1:32.456",
                  maxSpeed: "320 km/h",
                  pits: 1,
                },
                {
                  position: 2,
                  number: 33,
                  driver: "Max Verstappen",
                  car: "Red Bull",
                  laps: 58,
                  gap: "+1.234s",
                  lastLap: "1:33.789", // Added lastLap
                  bestLap: "1:32.789",
                  maxSpeed: "318 km/h",
                  pits: 1,
                },
                {
                  position: 1,
                  number: 44,
                  driver: "Lewis Hamilton",
                  car: "Mercedes",

                  laps: 58,
                  gap: "+0.000s",
                  lastLap: "1:33.456", // Added lastLap
                  bestLap: "1:32.456",
                  maxSpeed: "320 km/h",
                  pits: 1,
                },
                {
                  position: 2,
                  number: 33,
                  driver: "Max Verstappen",
                  car: "Red Bull",
                  laps: 58,
                  gap: "+1.234s",
                  lastLap: "1:33.789", // Added lastLap
                  bestLap: "1:32.789",
                  maxSpeed: "318 km/h",
                  pits: 1,
                },
  ] as Car[];

export default mockData;
