import type { Car } from "../util/carType";

const mockData: Car[] = [
  {
    position: 1,
    number: 44,
    driver: "Lewis Hamilton",
    car: "Mercedes",
    laps: 58,
    gap: "+0.000s",
    lastLap: "1:33.456",
    bestLap: "1:32.456",
    maxSpeed: "320 km/h",
    pits: 1,
    team: "Mercedes-AMG Petronas",
  },
  {
    position: 2,
    number: 33,
    driver: "Max Verstappen",
    car: "Red Bull",
    laps: 58,
    gap: "+1.234s",
    lastLap: "1:33.789",
    bestLap: "1:32.789",
    maxSpeed: "318 km/h",
    pits: 1,
    team: "Red Bull Racing",
  },
  {
    position: 3,
    number: 77,
    driver: "Valtteri Bottas",
    car: "Mercedes",
    laps: 58,
    gap: "+5.678s",
    lastLap: "1:34.123",
    bestLap: "1:33.123",
    maxSpeed: "316 km/h",
    pits: 1,
    team: "Mercedes-AMG Petronas",
  },
  {
    position: 4,
    number: 11,
    driver: "Sergio Pérez",
    car: "Red Bull",
    laps: 57,
    gap: "+1 Lap",
    lastLap: "1:34.456",
    bestLap: "1:33.456",
    maxSpeed: "314 km/h",
    pits: 2,
    team: "Red Bull Racing",
  },
  {
    position: 5,
    number: 16,
    driver: "Charles Leclerc",
    car: "Ferrari",
    laps: 57,
    gap: "+1 Lap",
    lastLap: "1:34.789",
    bestLap: "1:33.789",
    maxSpeed: "312 km/h",
    pits: 2,
    team: "Scuderia Ferrari",
  },
  {
    position: 6,
    number: 55,
    driver: "Carlos Sainz Jr.",
    car: "Ferrari",
    laps: 57,
    gap: "+1 Lap",
    lastLap: "1:35.123",
    bestLap: "1:34.123",
    maxSpeed: "310 km/h",
    pits: 2,
    team: "Scuderia Ferrari",
  },
  {
    position: 7,
    number: 4,
    driver: "Lando Norris",
    car: "McLaren",
    laps: 57,
    gap: "+1 Lap",
    lastLap: "1:35.456",
    bestLap: "1:34.456",
    maxSpeed: "308 km/h",
    pits: 2,
    team: "McLaren Racing",
  },
  {
    position: 8,
    number: 3,
    driver: "Daniel Ricciardo",
    car: "McLaren",
    laps: 56,
    gap: "+2 Laps",
    lastLap: "1:35.789",
    bestLap: "1:34.789",
    maxSpeed: "306 km/h",
    pits: 3,
    team: "McLaren Racing",
  },
  {
    position: 9,
    number: 14,
    driver: "Fernando Alonso",
    car: "Alpine",
    laps: 56,
    gap: "+2 Laps",
    lastLap: "1:36.123",
    bestLap: "1:35.123",
    maxSpeed: "304 km/h",
    pits: 3,
    team: "Alpine F1 Team",
  },
  {
    position: 10,
    number: 31,
    driver: "Esteban Ocon",
    car: "Alpine",
    laps: 56,
    gap: "+2 Laps",
    lastLap: "1:36.456",
    bestLap: "1:35.456",
    maxSpeed: "302 km/h",
    pits: 3,
    team: "Alpine F1 Team",
  },
];

export default mockData;
